# Site wide configuration

# https://jekyllrb.com/docs/liquid/filters/
url: ''
baseurl: ''

# The HTML language tag > https://www.w3.org/International/questions/qa-choosing-language-tags
lang: en

title: John Doe
description: Top performing project manager for Personal website about Ross Godwin' career

google_analytics_measurement_id: ''

linkedin:
  display-url: linkedin.com/johndoe
  url: https://www.linkedin.com/in/johndoe

github:
  display-url: github.com/johndoe
  url: https://www.github.com/johndoe










# Plugin: Pagination (jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 3
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled: true
  tags:
    enabled: true
    layouts:
      - autopage_tags.html
    permalink: /tag/:tag
  categories:
    enabled: false
    layouts:
      - autopage_category.html
  collections:
    enabled: false
    slugify:
      mode: 'ascii'
      cased: true

